### ISSUE TITLE
Update documentation for complex types

### ISSUE THREAD

**Issue by Nodd** [pyopencl/pyopencl#108]
The complex types were recently changed to use a struct instead of float2, but the documentation in http://documen.tician.de/pyopencl/array.html#complex-numbers is still for the old version. There is nothing about it in the changelog in http://documen.tician.de/pyopencl/misc.html#user-visible-changes.

It was very confusing for me when I came back to pyopencl and my code wasn't working anymore without any hints.

**Comment by inducer** [comment]
Thanks for the reminder. I had sent out an email with a poll about this at some point [1], but then forgot to update the docs when I went and did it. Sorry about the incompatible change. This is intended to be the big exception rather than the rule. The original behavior was broken enough that I thought the change was justified, and the number of bugs it uncovered in my code seemed to corroborate that assessment.

[1] http://lists.tiker.net/pipermail/pyopencl/2015-June/001895.html

**Comment by Nodd** [comment]
I'm fine with the incompatibility, it is sometimes necessary. In this case I discovered than I wasn't fully aware of the possible problems so I completely agree with the change. The new code is less readable but more correct !

I'd like to thank you for your work on this lib, I'm beginning to learn about gpu computing and it's way easier to do it with python than C !
