### ISSUE TITLE
symbol clEnqueue SVMMap, version OPENCL_2.0 not defined in libOpenCL.so.1

### ISSUE THREAD

**Issue by arghdos** [pyopencl/pyopencl#149]
Hi, I tried upgrading pyopencl to v2016.2 this morning, via 
`pip install pyopencl --upgrade`:

```
Collecting pyopencl
  Using cached pyopencl-2016.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg (from pyopencl)
Requirement already satisfied (use --upgrade to upgrade): pytools>=2015.1.2 in ./.local/lib/python2.7/site-packages (from pyopencl)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2 in ./.local/lib/python2.7/site-packages (from pyopencl)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.2.0 in ./.local/lib/python2.7/site-packages (from pyopencl)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in ./.local/lib/python2.7/site-packages (from pyopencl)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in ./.local/lib/python2.7/site-packages (from pyopencl)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in ./.local/lib/python2.7/site-packages (from pyopencl)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in ./.local/lib/python2.7/site-packages (from pytest>=2->pyopencl)
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./.local/lib/python2.7/site-packages (from cffi>=1.1.0->pyopencl)
Installing collected packages: pyopencl
  Running setup.py install for pyopencl: started
    Running setup.py install for pyopencl: finished with status 'done'
Successfully installed pyopencl-2016.2
```

However, upon import:

`python2.7 -c "import pyopencl"`

I get a crash:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nick/.local/lib/python2.7/site-packages/pyopencl/__init__.py", line 34, in <module>
    import pyopencl.cffi_cl as _cl
  File "/home/nick/.local/lib/python2.7/site-packages/pyopencl/cffi_cl.py", line 39, in <module>
    from pyopencl._cffi import ffi as _ffi
ImportError: /home/nick/.local/lib/python2.7/site-packages/pyopencl/_cffi.so: symbol clEnqueueSVMMap, version OPENCL_2.0 not defined in file libOpenCL.so.1 with link time reference
```

I think this has to do with the `SVMMap` in cffi_cl.py.  I do not have an OpenCL 2.0 compliant implementation (which AFAIK, is not available for an Intel CPU).  Instead I'm using the latest Intel OpenCL runtime/SDK (v16.1.1/v2016_6.2.0.1761 respectively)

**Comment by inducer** [comment]
A few comments:

* I think you might have an OpenCL 2.x header installed. If the header declares support for CL2, PyOpenCL will believe that and link against symbols from that.
* You can specifically ask it to not do that, by defining `CL_PRETEND_VERSION = "1.2"`(or some such) in `siteconf.py`.
* What matters for the error you got is whether your ICD *loader* (i.e. `libOpenCL.so`) is built to support OpenCL 2. (Both [OCL-ICD](https://github.com/OCL-dev/ocl-icd/) and the Khronos loader are. I'm not sure about the one Intel ships. I've not used that one in ages.) It seems your `libOpenCL.so` does not support CL2, and there's really no reason to not upgrade to one that does.
* You can absolutely use a CL2 ICD loader (and PyOpenCL built for CL2) with an ICD that only supports CL1.x.
* That said, both pocl and your version of Intel CL *do* support SVM (even if they don't fully support CL 2 just yet).

**Comment by arghdos** [comment]
@inducer I think it was picking actually up my CUDA CL headers which were first on the path. I was a bit unclear on the difference between the ICD and the ICD loader, so thanks for your comments on that.

I'm trying to get the Khronos loader built / installed.  I will close for now, as I expect that will resolve this issue.

**Comment by inducer** [comment]
FWIW, on Linux, I highly recommend ocl-icd over the Khronos thing.

**Comment by arghdos** [comment]
Thanks again for your help, the OCL-ICD w/ pretend version worked just fine

**Comment by jdumas** [comment]
Hi,

I have the exact same issue on arch-linux. Wouldn't it be possible to detect this error at runtime, and fallback to OpenCL 1.2 if the library doesn't support OpenCL 2.0 ?

**Comment by inducer** [comment]
Theoretically, yes. This would involve loading `libOpenCL.so` dynamically using `dlopen()` and calling all functions via `dlsym`, at a corresponding performance penalty.

Practically, it is the ICD loader's job to shield the application from this type of nonsense on the part of the ICDs. OCL-ICD does a competent job of that, so I am not inclined to act.

I claim that if this error occurs, the issue can always be traced back to a mistake on your part. For example, you may have let the Nvidia installer overwrite your system-supplied `libOpenCL.so` with Nvidia's broken one, at which point it is not a surprise that any header files or installed/distribution-supplied binaries no longer match up.

**Comment by jdumas** [comment]
I have both the OpenCL headers / Nvidia drivers installed via my package manager (`pacman` in archlinux), so if there is a mistake from our part, the fault lies in the package mainteners.

In archlinux, I have the following library files:
- `/usr/lib/OpenCL.so`, owned by system package `ocd-icd`
- `/opt/cuda/lib64/libOpenCL.so`, owned by syste package `cuda`

And I also have the following headers:
- `/usr/include/CL/cl.h` owned by system package `opencl-headers` (it has `CL_VERSION_2_1`).
- `/opt/cuda/include/CL/cl.h`, owned by the system package `cuda` package (this one only goes up to `CL_VERSION_1_2`).

See also the [arch wiki](https://wiki.archlinux.org/index.php/GPGPU) for the different packages available on this distro. Since `python-pypencl` is available directly in the [community](https://www.archlinux.org/packages/community/x86_64/python-pyopencl/) repository in archlinux, it would be nice if it could work out of the box.

In the end, I don't know exactly what is happening. Obviously, `pyopencl` is using `/usr/include/CL/cl.h` and expects OpenCL 2.0, but then I don't know what's going on when it loads the library `libOpenCL.so`.

**Comment by inducer** [comment]
> I don't know what's going on when it loads the library libOpenCL.so.

Use
```
python -m pip show pyopencl
```
to find the install location, then run
```
$ ldd /home/andreask/src/pyopencl/pyopencl/_cffi.so
	linux-vdso.so.1 (0x00007fff06bbe000)
	libOpenCL.so.1 => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007f0b973fc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0b9707a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0b96d75000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0b96b5e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0b96941000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0b9659f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0b9639b000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558bf2c09000)
```
This shows you what `libOpenCL.so` is being used. My guess it's the Nvidia one, because they've likely bent up something in your dynamic linker configuration. FWIW, the `libOpenCL.so` shipped by Nvidia will not match your header (or the rest of your system). Nvidia needlessly ships an obsolete `libOpenCL.so`, just to be difficult. It's safe to delete.

**Comment by jdumas** [comment]
Yes it was linking with the Nvidia library. Damn what a headache. I've removed the `libOpenCL.so` from Nvidia and it seems to work now. Too bad I have to do that manually (and every time I update the `cuda` package I guess).
