### ISSUE TITLE
array.py: allow 'u' additional to 'i' for subscript.dtype.kind and index.dtype.kind

### ISSUE THREAD

**Issue by inferrna** [pyopencl/pyopencl#71]
In functions `__getitem__` and `__setitem__` signed integer types is only allowed for indexing. Is there any reason for disallowing unsigned indexes? Unfortunately my memory supports only positive addressing and I would like to be able to use unsigned indexing too.

**Comment by yuyichao** [comment]
Do you mean:

In functions `__getitem__` and **`__setitem__`** only signed integer types is allowed for indexing. Is there any reason for disallowing **unsigned** indexes? Unfortunately my memory supports only positive addresses and I would like to be able to use **unsigned** indexing too.

**Comment by inferrna** [comment]
Yes, thank you, I was in a hurry.

**Comment by inferrna** [comment]
Piece of array.py, for example:
```
        if isinstance(subscript, Array):
            if subscript.dtype.kind != "i":
                raise TypeError(
                        "fancy indexing is only allowed with integers")
```

**Comment by inducer** [comment]
PyOpenCL allows negative strides, so index math with negative values *will* occur in kernels. So we need to use signed types for indices there. So if your indices are small enough to fit into a signed integer, then you might as well use those (or use a signed view--since the bit pattern is the same between signed and unsigned). If you need that one bit of extra range provided by unsigned ones, PyOpenCL has no way to generate correct indexing code for you--because it must use signed integers internally, and the calculations with signed integers are guaranteed to overflow.

FWIW, numpy has the same restriction--all index arrays are converted to `numpy.intp` (i.e. signed, pointer-sized integers) before being used as indices.
