### ISSUE TITLE
[py3] ImportError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by ignatenkobrain** [pyopencl/pyopencl#95]
```python
test_wrapper.py:31: in <module>
    import pyopencl as cl
../../../BUILDROOT/python-pyopencl-2015.2-1.fc24.x86_64/usr/lib64/python3.4/site-packages/pyopencl/__init__.py:35: in <module>
    import pyopencl.cffi_cl as _cl
../../../BUILDROOT/python-pyopencl-2015.2-1.fc24.x86_64/usr/lib64/python3.4/site-packages/pyopencl/cffi_cl.py:36: in <module>
    from pyopencl._cffi import ffi as _ffi
E   ImportError: No module named '_cffi_backend'
```

I don't see this error on python2, probably something needs to be tuned. I have the same commands for building python2 and python3 versions.

**Comment by inducer** [comment]
FWIW, the package builds and works fine for me on Py3. CFFI backend is part of `cffi`--maybe that's not fully/correctly installed?

**Comment by ignatenkobrain** [comment]
yes, really! weird that I got python2-cffi installed. Thanks for information!

**Comment by BHushanRathod** [comment]
I'm getting this error while installing cryptography package on my ubuntu 14.04 machine. i tried installing all dependencies listed on official site as `$ sudo apt-get install build-essential libssl-dev libffi-dev python-dev`  still getting the `No module named _cffi_backend` error. if anyone get whats happening please help.. Thanks

**Comment by itJunky** [comment]
I have same error too, and installation build-essential libssl-dev libffi-dev python-dev doesn't help.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by itJunky** [comment]
i don't know where this maillist. But i found this issue in google and some other people can found it if needed. And if here we write a solution, many people get helps.

**Comment by bodedra** [comment]
I resolved it with following command.

    python3 -m pip install cffi

**Comment by wshamasneh** [comment]
Can this issue be resolved on Windows environment?

**Comment by ghost** [comment]
It may be simply due to a version mismatch of the python compiler runtime and later on execution runtime.

The compiled shared object's filename consists of compiler, platform, architecture and python version reference in addition to the _cffi_backend identifier for lookups.
In my case I ended up with a '_cffi_backend.cpython-37m-x86_64-linux-gnu.so' file. It is obvious (from reading the filename) that I compiled with a python 3.7.x runtime version. It was executed on a 3.6.x runtime version though (causing the described error). I guess that upon execution the filename is parsed and probed for compatibility. If the python runtime version is a mismatch, it will simply ignore the shared object. After I adopted the execution runtime to reflect version 3.7.x it worked flawlessly.

**Comment by DevangMstryls** [comment]
> I resolved it with following command.
> 
> ```
> python3 -m pip install cffi
> ```

In my case it didn't work even after installing, and then I realised that a venv is activated. 
So, I ran `$ deactivate` and installed again and it worked fine!

**Comment by kushhsuk** [comment]
Got here from Google because I was trying to install the python library "Paramiko" on AWS Lambda and was running into this same problem.

Some things I found out are that you need to build the paramiko library and its dependencies on the same OS with the same architecture as AWS Lambda. This can mean some docker environment (didn't work for me), or AWS cloudshell, which should be the easiest way. Install the libraries in there, and download them out locally and make a layer out of it. HOWEVER, keep in mind that cloudshell uses python3.7 currently, so your lambda needs to run the same version if using python.

If you're lazy and just need Paramiko on Lambda, use a premade public AWS layer: https://github.com/jetbridge/paramiko-lambda-layer
